import { Product, User, Comment } from '../types';

export const currentUserMock: User = {
  id: 'u1',
  username: 'ayu_lestari',
  fullName: 'Ayu Lestari',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  bio: 'Merangkai produk lokal dengan penuh cerita ✨ Bandung · Terima pesanan melalui WhatsApp',
  location: 'Bandung, Jawa Barat',
  whatsappNumber: '+6281234567890',
  productsCount: 9,
  followersCount: 1200,
};

export const otherUsersMock: Record<string, User> = {
  dapur_nisa: {
    id: 'u2',
    username: 'dapur_nisa',
    fullName: 'Dapur Nisa',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    bio: 'Kue kering & hampers buatan rumah kualitas premium 🍪 Bandung',
    location: 'Bandung, Jawa Barat',
    whatsappNumber: '+6281987654321',
    productsCount: 12,
    followersCount: 2400,
  },
  kopi_senja: {
    id: 'u3',
    username: 'kopi_senja',
    fullName: 'Kopi Senja Utama',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    bio: 'Cold brew & kopi susu gula aren lokal berkualitas ☕ Bandung',
    location: 'Bandung, Jawa Barat',
    whatsappNumber: '+6281345678901',
    productsCount: 8,
    followersCount: 1850,
  },
  jowi_lokal: {
    id: 'u4',
    username: 'jowi_lokal',
    fullName: 'joko wilo',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    bio: 'Merangkai produk lokal dengan penuh cerita ✨ Bandung · Terima pesanan melalui WhatsApp',
    location: 'Bandung, Jawa Barat',
    whatsappNumber: '+6281567890123',
    productsCount: 9,
    followersCount: 1200,
  },
};

export const initialProductsMock: Product[] = [
  {
    id: 'p1',
    userId: 'u2',
    username: 'dapur_nisa',
    userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    userLocation: 'Bandung, Jawa Barat',
    title: 'Nusantara Kitchen Artisan Cookies Box',
    category: 'Makanan',
    price: 85000,
    imageUrl: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=1000&q=80',
    caption: 'dapur_nisa Cookies gula aren yang renyah, dipanggang segar setiap pagi. Siap menemani waktu santaimu 🍪',
    hashtags: ['#kulinerbandung', '#cookiesgulaaren', '#umkmlokal'],
    likesCount: 142,
    commentsCount: 3,
    createdAt: '2 jam yang lalu',
  },
  {
    id: 'p2',
    userId: 'u3',
    username: 'kopi_senja',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    userLocation: 'Bandung, Jawa Barat',
    title: 'Kopi Susu Gula Aren 250ml',
    category: 'Minuman',
    price: 25000,
    imageUrl: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=1000&q=80',
    caption: 'kopi_senja Cold brew gula aren dengan biji kopi pilihan dari petani lokal.',
    hashtags: ['#kopisusuaren', '#coldbrew', '#kopibandung'],
    likesCount: 98,
    commentsCount: 1,
    createdAt: '2 jam yang lalu',
  },
  {
    id: 'p3',
    userId: 'u4',
    username: 'jowi_lokal',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    userLocation: 'Bandung, Jawa Barat',
    title: 'Aneka Jam & Selai Buah Organik',
    category: 'Makanan',
    price: 45000,
    imageUrl: 'https://images.unsplash.com/photo-1589733955941-5eeaf752f6dd?auto=format&fit=crop&w=1000&q=80',
    caption: 'Selai buah segar tanpa pengawet buatan buatan rumahan lokal.',
    hashtags: ['#selaiorganik', '#kulinerlokal'],
    likesCount: 76,
    commentsCount: 2,
    createdAt: '4 jam yang lalu',
  },
  {
    id: 'p4',
    userId: 'u4',
    username: 'jowi_lokal',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    userLocation: 'Bandung, Jawa Barat',
    title: 'Tas Anyaman Rotan Etnik',
    category: 'Kriya',
    price: 135000,
    imageUrl: 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=1000&q=80',
    caption: 'Tas rotan handmade khas pengrajin lokal, estetik & kokoh.',
    hashtags: ['#tasrotan', '#kriyalokal'],
    likesCount: 215,
    commentsCount: 5,
    createdAt: '5 jam yang lalu',
  },
  {
    id: 'p5',
    userId: 'u4',
    username: 'jowi_lokal',
    userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    userLocation: 'Bandung, Jawa Barat',
    title: 'Sambal Bajak Rumahan Premium',
    category: 'Makanan',
    price: 30000,
    imageUrl: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=1000&q=80',
    caption: 'Sambal bajak pedas gurih khas nusantara dari cabai segar.',
    hashtags: ['#sambalbajak', '#sambalnusantara'],
    likesCount: 164,
    commentsCount: 4,
    createdAt: '6 jam yang lalu',
  },
  {
    id: 'p6',
    userId: 'u1',
    username: 'ayu_lestari',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    userLocation: 'Bandung, Jawa Barat',
    title: 'Sabun Herbal Alami Organic',
    category: 'Kriya',
    price: 35000,
    imageUrl: 'https://images.unsplash.com/photo-1607006482602-76ca072b445f?auto=format&fit=crop&w=1000&q=80',
    caption: 'Sabun batang alami terbuat dari minyak kelapam essential oil & rempah herbal.',
    hashtags: ['#sabunherbal', '#organicskincare'],
    likesCount: 88,
    commentsCount: 2,
    createdAt: '1 hari yang lalu',
  },
  {
    id: 'p7',
    userId: 'u1',
    username: 'ayu_lestari',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    userLocation: 'Bandung, Jawa Barat',
    title: 'Keripik Pisang Renyah Island Harvest',
    category: 'Makanan',
    price: 20000,
    imageUrl: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?auto=format&fit=crop&w=1000&q=80',
    caption: 'Keripik pisang pilihan renyah dengan taburan gula aren organik.',
    hashtags: ['#keripikpisang', '#camilanlokal'],
    likesCount: 110,
    commentsCount: 0,
    createdAt: '1 hari yang lalu',
  },
  {
    id: 'p8',
    userId: 'u1',
    username: 'ayu_lestari',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    userLocation: 'Bandung, Jawa Barat',
    title: 'Kain Batik Tulis Tradisional',
    category: 'Pakaian',
    price: 250000,
    imageUrl: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=80',
    caption: 'Kain batik motif klasik karya pembatik lokal Jawa Barat.',
    hashtags: ['#batiktulis', '#wasthabatik'],
    likesCount: 320,
    commentsCount: 7,
    createdAt: '2 hari yang lalu',
  },
  {
    id: 'p9',
    userId: 'u1',
    username: 'ayu_lestari',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    userLocation: 'Bandung, Jawa Barat',
    title: 'Kue Lapis Legit Rempah Spesial',
    category: 'Makanan',
    price: 180000,
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1000&q=80',
    caption: 'Lapis legit berlapis rempah mentega premium, pas untuk bingkisan keluarga.',
    hashtags: ['#lapislegit', '#kuespesial'],
    likesCount: 290,
    commentsCount: 3,
    createdAt: '2 hari yang lalu',
  },
];

export const initialCommentsMock: Record<string, Comment[]> = {
  p1: [
    {
      id: 'c1',
      productId: 'p1',
      username: 'rani_kriya',
      userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
      content: 'Kemasannya cantik sekali! Apakah bisa pesan untuk hampers ulang tahun?',
      createdAt: '1 jam yang lalu',
      replies: [
        {
          id: 'c2',
          productId: 'p1',
          username: 'dapur_nisa',
          userAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
          content: 'Bisa, Kak! Kami juga menyediakan kartu ucapan khusus ✨',
          createdAt: '45 menit yang lalu',
        },
      ],
    },
    {
      id: 'c3',
      productId: 'p1',
      username: 'bima.foodies',
      userAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
      content: 'Sudah coba dan memang renyah. Gula arennya pas, tidak terlalu manis.',
      createdAt: '30 menit yang lalu',
    },
  ],
};
